title: Arely Miramontes Rodríguez
occupation: Full-Stack Web Developer & Mentor
description: Portfolio site for your friendly neighboorhood SpiderDev.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github: {
      repository_url: https://github.com/ArelySkywalker/ArelySkywalker.github.io
}